"""MIDI files, Ableton-aligned stems, the recreation guide and zip packs."""
import json
import zipfile
from pathlib import Path

import mido
import numpy as np
import soundfile as sf

from ..config import SR

TPB = 480


def midi_text(s: str, limit: int = 60) -> str:
    """MIDI meta text is Latin-1: keep accents that fit, replace the rest (e.g. Cyrillic) with '?'."""
    return (s or "")[:limit].encode("latin-1", "replace").decode("latin-1")


def velocity(n: dict) -> int:
    if "vel" in n:
        return int(n["vel"])
    return int(np.clip(35 + 92 * n.get("a", 0.5), 1, 127))


def _track(name: str, notes: list[dict], q: float | None, channel: int = 0) -> mido.MidiTrack:
    tr = mido.MidiTrack()
    tr.append(mido.MetaMessage("track_name", name=midi_text(name), time=0))
    ev = []
    for n in notes:
        s, e = n["bs"], n.get("be", n["bs"] + 0.25)
        if q:
            s = round(s / q) * q
            e = max(s + q, round(e / q) * q)
        if s < 0:
            continue
        p = int(n.get("note", n.get("p", 60)))
        ts, te = int(round(s * TPB)), int(round(e * TPB))
        ev.append((ts, 1, mido.Message("note_on", note=p, velocity=velocity(n), channel=channel)))
        ev.append((te, 0, mido.Message("note_off", note=p, velocity=0, channel=channel)))
    ev.sort(key=lambda x: (x[0], x[1]))
    last = 0
    for t, _, msg in ev:
        msg.time = t - last
        last = t
        tr.append(msg)
    tr.append(mido.MetaMessage("end_of_track", time=0))
    return tr


def write_midi(path: Path, tracks: list[tuple[str, list[dict], int]], bpm: float, meter: int,
               q: float | None = None, title: str = "") -> None:
    mid = mido.MidiFile(type=1, ticks_per_beat=TPB)
    meta = mido.MidiTrack()
    meta.append(mido.MetaMessage("track_name", name=midi_text(title) or "Tempo", time=0))
    meta.append(mido.MetaMessage("set_tempo", tempo=mido.bpm2tempo(bpm), time=0))
    meta.append(mido.MetaMessage("time_signature", numerator=meter, denominator=4, time=0))
    meta.append(mido.MetaMessage("end_of_track", time=0))
    mid.tracks.append(meta)
    for name, notes, ch in tracks:
        mid.tracks.append(_track(name, notes, q, ch))
    mid.save(str(path))


def drum_notes(hits: dict) -> list[dict]:
    out = []
    for hs in hits.values():
        for h in hs:
            out.append({"bs": h["beat"], "be": h["beat"] + 0.25, "note": h["note"], "vel": h["vel"]})
    return sorted(out, key=lambda n: n["bs"])


def aligned_stem(src: Path, dst: Path, origin_time: float, gain: float) -> None:
    """Shift a stem so bar 1 is at 0 s and restore the original level (float WAV)."""
    x, _ = sf.read(str(src), dtype="float32", always_2d=True)
    x = x / gain
    off = int(round(origin_time * SR))
    if off > 0:
        x = x[off:]
    elif off < 0:
        x = np.concatenate([np.zeros((-off, x.shape[1]), np.float32), x])
    # 24-bit when it can't clip at the original level, 32-bit float otherwise
    sf.write(str(dst), x, SR, subtype="PCM_24" if np.abs(x).max() < 0.999 else "FLOAT")


def guide_markdown(A: dict) -> str:
    g = A["global"]
    L = []
    L.append(f"# {A['track']['title']} - recreation guide\n")
    L.append("Generated by Track Anatomy. Everything below comes from automatic analysis of separated "
             "stems: treat it as a strong first draft and trust your ears where they disagree. "
             "Note names follow Ableton (C3 = middle C).\n")
    L.append("## Project settings\n")
    if g.get("has_beat") is False:
        L.append("- **Tempo:** no clear beat; bars use a 120 BPM placeholder grid (read them as time markers)")
    else:
        L.append(f"- **Tempo:** {g['bpm']:.2f} BPM" + ("" if g["steady"] else " (drifts: warp the stems to the grid)"))
    L.append(f"- **Time signature:** {g['meter']}/4")
    if g["key"].get("clear") is False:
        L.append(f"- **Key:** unclear (best guess {g['key']['name']}; not enough tonal material)")
    else:
        L.append(f"- **Key:** {g['key']['name']} (scale: {' '.join(g['key']['scale'])})")
    sw = A.get("drums", {}).get("swing")
    if sw and sw.get("straight"):
        L.append("- **Swing:** none: program the drums straight on the grid")
    elif sw:
        L.append(f"- **Swing:** ~{sw['percent']:.0f}% on {sw['grid']} notes (50% = straight): "
                 f"apply a Groove Pool swing of about {sw['percent']:.0f}%")
    L.append(f"- **Length:** {g['n_bars']} bars; bar 1 starts {g['origin_time']:.3f} s into the file")
    L.append("")
    L.append("## Arrangement\n")
    L.append("| Section | Bars | Length | Changes | What's playing |")
    L.append("|---|---|---|---|---|")
    names = {e["id"]: e["name"] for e in A["elements"]}
    prev: list = []
    for i, s in enumerate(A["sections"]):
        els = ", ".join(names.get(k, k) for k in s["elements"])
        ins = [f"+{names.get(k, k)}" for k in s["elements"] if k not in prev]
        outs = [f"-{names.get(k, k)}" for k in prev if k not in s["elements"]]
        chg = "start" if i == 0 else (", ".join(ins + outs) or "same parts")
        key = f" ({s['key']})" if s.get("key") else ""
        L.append(f"| {s['label']}{key} | {s['b0'] + 1}-{s['b1']} | {s['bars']} bars | {chg} | {els} |")
        prev = s["elements"]
    L.append("")
    if A.get("fx_events"):
        L.append("### Transitions and FX\n")
        for e in A["fx_events"]:
            where = f"bar {e['bar0'] + 1}" if e["bar0"] == e["bar1"] else f"bars {e['bar0'] + 1}-{e['bar1']}"
            L.append(f"- {where}: {e['label']}" + (f" ({e['detail']})" if e.get("detail") else ""))
        L.append("")
    D = A.get("drums", {})
    if D.get("present"):
        L.append("## Drum patterns\n")
        steps = D["steps_per_bar"]
        spb = D["steps_per_beat"]
        L.append(f"Grid: {steps} steps per bar ({'16ths' if spb == 4 else 'triplets'}). `X` = accent, `x` = hit, `o` = open hat.\n")
        lanes = {l["key"]: l for l in D["lanes"]}
        for p in D["patterns"][:6]:
            L.append(f"**Pattern {p['id']}**: {p['count']} bars (e.g. bars {', '.join(str(b + 1) for b in p['bars'][:8])}"
                     f"{'...' if len(p['bars']) > 8 else ''})\n")
            L.append("```")
            head = "".join(str(i // spb + 1) if i % spb == 0 else "." for i in range(steps))
            L.append(f"{'':12s} {head}")
            for k, v in p["grid"].items():
                lab = lanes[k]["label"] if k in lanes else k
                row = "".join(("o" if lanes.get(k, {}).get("note") == 46 else ("X" if s >= 100 else "x")) if s else "-" for s in v)
                L.append(f"{lab[:12]:12s} {row}")
            L.append("```\n")
        seq = D["bar_pattern"]
        L.append("Pattern per bar: `" + " ".join(s or "." for s in seq) + "`\n")
    if A.get("chords"):
        L.append("## Chords\n")
        for s in A["sections"]:
            lp = s.get("chord_loop")
            if lp:
                L.append(f"- **{s['label']}** ({lp['bars']}-bar loop): " + " | ".join(lp["chords"]))
            elif s.get("chord_bars"):
                L.append(f"- **{s['label']}**: " + " | ".join(" ".join(b) or "-" for b in s["chord_bars"]))
        L.append("")
    L.append("## Elements\n")
    for e in A["elements"]:
        L.append(f"### {e['name']}\n")
        f = e.get("features", {})
        ns = f.get("notes")
        if ns:
            L.append(f"- Range {ns['low']}-{ns['high']}, {ns['count']} notes, typical length {ns['typical_length']}, "
                     f"{'monophonic' if ns['mono'] else 'up to ' + str(ns['max_polyphony']) + ' notes at once'}")
        sg = e.get("suggest")
        if sg:
            L.append(f"- **Start with:** {sg['device']}")
            for t in sg["tips"]:
                L.append(f"- {t}")
            for t in sg["fx"]:
                L.append(f"- FX: {t}")
        if e.get("midi"):
            L.append(f"- MIDI: `midi/{Path(e['midi']).name}`")
        L.append("")
    L.append("## Import into Ableton\n")
    L.append("**Easiest:** open the `.als` in the project folder. It is set to the right tempo and time signature, "
             "has a locator at every section, a MIDI track per part (drop your instruments on them: a Drum Rack on "
             "the drums track) and every separated stem on an audio track, aligned to bar 1 and warped to the grid. "
             "The Groove Pool contains a **Track Anatomy groove** measured from the drums: apply it to your "
             "MIDI clips to get the original swing and feel. "
             "If Live reports missing samples, point it at the `Samples/Imported` folder.\n")
    L.append("By hand:\n")
    L.append(f"1. Set the tempo to {g['bpm']:.2f} and the time signature to {g['meter']}/4.")
    L.append("2. Drag the files from `Samples/Imported/` onto audio tracks at bar 1 (they are pre-aligned so bar 1 = 0 s). "
             "Turn Warp off or set the clip's tempo to the project tempo.")
    L.append("3. Drag the files from `MIDI/` onto MIDI tracks at bar 1. `drums.mid` uses the Drum Rack layout "
             "(C1 kick, D1 snare, F#1 closed hat, A#1 open hat, C#2 crash, D#2 ride).")
    L.append("4. Use the stems as a reference: A/B your sounds against them, then mute them.")
    return "\n".join(L)


def safe_name(s: str, max_bytes: int = 120) -> str:
    """A title usable as a file/folder name on Windows, macOS and Linux (length-limited in bytes)."""
    s = "".join(ch for ch in s if ch not in '<>:"/\\|?*' and ord(ch) >= 32).strip().rstrip(". ")
    while len(s.encode("utf-8")) > max_bytes:
        s = s[:-1]
    return s.rstrip(". ") or "Track"


def build_project(track_dir: Path, A: dict, out_dir: Path, abs_root: str = "") -> Path | None:
    """An Ableton project folder: the .als, Samples/Imported/*.wav (bar-1 aligned), MIDI/, GUIDE.md.
    Returns the .als path, or None when Live's template isn't available (stems + MIDI only)."""
    import shutil

    from . import als
    out_dir.mkdir(parents=True, exist_ok=True)
    als_path = None
    if als.available():
        als_path = als.build(A, track_dir, out_dir, abs_root)
    else:
        samples = out_dir / "Samples" / "Imported"
        samples.mkdir(parents=True, exist_ok=True)
        for e in A["elements"]:
            src = track_dir / e["audio"]
            if src.exists():
                aligned_stem(src, samples / f"{e['id']}.wav", A["global"]["origin_time"], A["track"]["gain"])
    mdir = out_dir / "MIDI"
    mdir.mkdir(exist_ok=True)
    for p in sorted((track_dir / "midi").glob("*.mid")):
        shutil.copyfile(p, mdir / p.name)
    (out_dir / "GUIDE.md").write_text(guide_markdown(A), encoding="utf-8")
    return als_path


def build_zip(track_dir: Path, A: dict, with_stems: bool, out: Path | None = None) -> Path:
    """Zip either the full Ableton project (with_stems) or just MIDI + guide + analysis.
    Written to a temporary name and renamed, so a crash never leaves a truncated zip."""
    import os
    import shutil
    import tempfile
    out = out or track_dir / ("export_full.zip" if with_stems else "export_midi.zip")
    base = safe_name(A["track"]["title"])
    part = out.with_name(out.name + ".part")
    if with_stems:
        tmp_root = Path(tempfile.mkdtemp(dir=track_dir, prefix="project-"))
        try:
            proj = tmp_root / f"{base} Project"
            build_project(track_dir, A, proj)
            with zipfile.ZipFile(part, "w", zipfile.ZIP_DEFLATED) as z:
                for p in sorted(proj.rglob("*")):
                    if p.is_file():
                        z.write(p, str(p.relative_to(tmp_root)),
                                compress_type=zipfile.ZIP_STORED if p.suffix == ".wav" else zipfile.ZIP_DEFLATED)
        finally:
            shutil.rmtree(tmp_root, ignore_errors=True)
    else:
        with zipfile.ZipFile(part, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr(f"{base}/GUIDE.md", guide_markdown(A))
            for p in sorted((track_dir / "midi").glob("*.mid")):
                z.write(p, f"{base}/MIDI/{p.name}")
            z.writestr(f"{base}/analysis.json", json.dumps(A, indent=1))
    os.replace(part, out)
    return out
